CREATE TABLE specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    address VARCHAR(200),
    consultation_fee DOUBLE PRECISION,
    biography VARCHAR(1000),
    gender VARCHAR(10),
    profile_picture VARCHAR(200),
    specialty_id BIGINT,
    password VARCHAR(100) NOT NULL,
    FOREIGN KEY (specialty_id) REFERENCES specialties(id)
);

CREATE TABLE availabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    date DATE NOT NULL,
    day_of_week VARCHAR(20) NOT NULL,
    time_slot VARCHAR(20) NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES users(id)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    appointment_date DATE NOT NULL,
    day VARCHAR(20) NOT NULL,
    reason VARCHAR(200),
    time_slot VARCHAR(20) NOT NULL,
    consultation_fee DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES users(id),
    FOREIGN KEY (doctor_id) REFERENCES users(id)
);